name: CustomSpawns
author: Bencor29
website: http://bencor29.livehost.fr
version: 1.4.3
softdepend: [Multiverse-Core, WorldGuard]
main: fr.bencor29.customspawns.CustomSpawns
commands:
  spawn:
    description: Vous tp vers le spawn du monde.
    usage: /spawn
  lobby:
    description: Vous tp vers le lobby.
    usage: /lobby
  group:
    description: Gere les groupes.
    usage: /group [list | create <group> <world_spawn> | remove <group> | addworld <group> <world> | delworld <group> <world> | listworlds <group> | setworldspawn <group>]
    permission: customspawns.admin
  setlobby:
    description: Gere le lobby.
    usage: /setlobby
    permission: customspawns.admin
  csreload:
    description: Recharge le plugin.
    usage: /csreload
    permission: customspawns.admin